Fix 513 dotnet sdk
XeroAPI/Xero-NetStandard pull request #531
Opened 2024-08-13 10:10 UTC by sangeet-joy-tw

2024-08-14 07:19 UTC, Raghunath-S-S-J approved these changes

2024-08-21 12:10 UTC, manishT72 requested changes
Also check file download feature. SDK should be able to upload the file with correct encoding and user should be able to download and open the file.

2024-08-21 12:10 UTC, manishT72 commented on Xero.NetStandard.OAuth2.Test/Helpers/JsonDoc.cs
> +            var output = deserializer.Deserialize<TModel>(response).Result;
use await and avoid .Result

2024-08-21 12:10 UTC, manishT72 commented on Xero.NetStandard.OAuth2.Test/Model/Bankfeeds/CreditDebitIndicatorTests.cs
> +            var actual = await deserializer.Deserialize<CountryCode>(response);
Revert to CreditDebitIndicator

2024-08-21 12:10 UTC, manishT72 commented on Xero.NetStandard.OAuth2.Test/Model/Bankfeeds/CurrencyCodeTests.cs
> +            var actual = await deserializer.Deserialize<CountryCode>(response);
Revert to CurrencyCode

2024-08-21 12:10 UTC, manishT72 commented on Xero.NetStandard.OAuth2.Test/Model/PayrollAu/AccountTests.cs
> +using Xero.NetStandard.OAuth2.Model.Bankfeeds;
Is this namespace needed?

2024-08-21 12:10 UTC, manishT72 commented on Xero.NetStandard.OAuth2/Client/ApiClient.cs
> +            IList<string> headers = response.Headers.Select(x => x.Key + "=" + x.Value).ToList();
Use string interpolation instead of + operator

2024-08-21 12:10 UTC, manishT72 commented on Xero.NetStandard.OAuth2/Client/ApiClient.cs
> +        public JsonSerializerSettings SerializerSettings { get; set; } = new JsonSerializerSettings
Can this be private and we can re-use the previously defined setting from CustomJsonCodec

2024-08-21 12:10 UTC, manishT72 commented on Xero.NetStandard.OAuth2/Client/Configuration.cs
> +        public X509CertificateCollection ClientCertificates { get; }
Can we please remove these?

2024-08-22 12:52 UTC, manishT72 approved these changes

2024-08-22 13:21 UTC, merged